alias c='clear'
alias go='cd -P'
alias la='/bin/ls -Al'
alias lc='/bin/ls -ltcr'
alias lk='/bin/ls -lSr'
alias ll='/bin/ls -lah'
alias lr='/bin/ls -lR'
alias lt='/bin/ls -ltr'
alias lu='/bin/ls -ltur'
alias lx='/bin/ls -lXB'

alias d7='cd /Users/andy/Sites/d7/; php -S localhost:8000 /Users/andy/Sites/d7/routing.php'

alias gs='git status'
alias gd='git diff'
alias gc='git commit'
alias gp='git push'
alias cw='compass watch'
alias g:pl:o:m='git pull origin master'
alias g:pl='git pull'
alias g:s='git status'

alias dtr='drush test-clean; drush test-run --dirty --field-labels=0'

# alias composer='hhvm /usr/local/bin/composer'
